[versions]
codion = "0.18.63"
flatlaf = "3.6.2"
h2 = "2.3.232"
javalin = "6.7.0"
jackson = "2.19.1"
jasperreports = "7.0.3"
jfreechart = "1.5.6"

[libraries]
codion-framework-bom = { module = "is.codion:codion-framework-bom", version.ref = "codion" }
codion-common-rmi = { module = "is.codion:codion-common-rmi" }
codion-dbms-h2 = { module = "is.codion:codion-dbms-h2" }
codion-tools-loadtest-ui = { module = "is.codion:codion-tools-loadtest-ui" }
codion-framework-domain = { module = "is.codion:codion-framework-domain" }
codion-framework-domain-test = { module = "is.codion:codion-framework-domain-test" }
codion-framework-db-core = { module = "is.codion:codion-framework-db-core" }
codion-framework-db-rmi = { module = "is.codion:codion-framework-db-rmi" }
codion-framework-db-local = { module = "is.codion:codion-framework-db-local" }
codion-framework-db-http = { module = "is.codion:codion-framework-db-http" }
codion-framework-json-domain = { module = "is.codion:codion-framework-json-domain" }
codion-tools-generator-model = { module = "is.codion:codion-tools-generator-model" }
codion-swing-framework-ui = { module = "is.codion:codion-swing-framework-ui" }
codion-tools-generator-ui = { module = "is.codion:codion-tools-generator-ui" }
codion-tools-jul-classpath = { module = "is.codion:codion-tools-jul-classpath" }
codion-plugin-jasperreports = { module = "is.codion:codion-plugin-jasperreports" }
codion-plugin-logback-proxy = { module = "is.codion:codion-plugin-logback-proxy" }
codion-plugin-hikari-pool = { module = "is.codion:codion-plugin-hikari-pool" }
codion-plugin-flatlaf = { module = "is.codion:codion-plugin-flatlaf" }
codion-plugin-flatlaf-intellij-themes = { module = "is.codion:codion-plugin-flatlaf-intellij-themes" }
codion-framework-server = { module = "is.codion:codion-framework-server" }
codion-framework-servlet = { module = "is.codion:codion-framework-servlet" }
codion-tools-monitor-ui = { module = "is.codion:codion-tools-monitor-ui" }
codion-tools-swing-mcp = { module = "is.codion:codion-tools-swing-mcp" }

javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
jasperreports-jdt = { module = "net.sf.jasperreports:jasperreports-jdt", version.ref = "jasperreports" }
jasperreports-pdf = { module = "net.sf.jasperreports:jasperreports-pdf", version.ref = "jasperreports" }
jfreechart = { module = "org.jfree:jfreechart", version.ref = "jfreechart" }
flatlaf-extras = { module = "com.formdev:flatlaf-extras", version.ref = "flatlaf" }